
services:
  frontend:
    build:
      context: ./foosthebill-app/
    container_name: foosthebill-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./foosthebill-api/
    container_name: foosthebill-backend
    ports:
      - "3002:3001" 
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_NAME=foosthebill
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: foosthebill
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
